version: "3"

services:

  catfact-ui:
    image: catfact:client
    build: ./catfact-client
    expose:
      - "80"
    networks:
      mesh:
        aliases:
          - catfact-ui

  grpc-server:
    image: grpc:server
    build: ./grpc-server
    expose:
      - "80"
    networks:
      mesh:
        aliases:
          - grpc-server

  envoy:
    image: envoy:front
    build: ./envoy
    ports: 
      - "8080:8080"
    networks:
      mesh:
        aliases:
          - envoy-front

networks:
  mesh:
