version: "3"

services:

  grpc-server:
    image: grpc:server
    build: ./grpc-server
    expose:
      - "7777"
    networks:
      mesh:
        aliases:
          - grpc-server

  envoy:
    image: envoy:sidecar
    build: ./envoy
    ports: 
      - "8080:8080"
    networks:
      mesh:
        aliases:
          - envoy-sidecar

networks:
  mesh:
