version: "3"

services:

  grpc-server:
    image: grpc:server
    build: ./grpc-server
    expose:
      - "7777"

  envoy:
    image: envoy:sidecar
    build: ./envoy
    ports: 
      - "8080:8080"
    links:
      - grpc-server
